name: "Hexesoft Mitsubishi"
description: "Bridge Mitsubishi in Home Assistant"
version: "1.2.0"
slug: "hexesoft_mitsubishi"
arch:
  - aarch64
  - amd64
init: false
map:
  - config:rw

options:
  mitsubishi:
    host: ""
    polling_interval: 10
    operating_mode: "integrated"
    bticino_base_topic: "bticino_bridge"
    heating_boost_delta: 3.0
    cooling_boost_delta: 0.0

  air_conditioners:
    devices: []

  hydronics:
    devices: []

  mqtt:
    host: ""
    port: 1883
    username: ""
    password: ""
    base_topic: "mitsubishi_bridge"
    discovery_prefix: "homeassistant"
    
  advanced:
    log_level: "info"

schema:
  mitsubishi:
    host: str
    polling_interval: int(5,)
    operating_mode: list(standard|integrated)
    bticino_base_topic: str
    heating_boost_delta: float
    cooling_boost_delta: float
  
  air_conditioners:
    devices:
      - name: str
        id: str
        bticino_zone: str?
        supports_dry: bool?
        
  hydronics:
    devices:
      - name: str
        id: str
        type: list(HOT_WATER|HEATING)
      
  mqtt:
    host: str
    port: port
    username: str?
    password: password?
    base_topic: str
    discovery_prefix: str
    
  advanced:
    log_level: list(debug|info|warning|error)